language: ruby
rvm:
  - 2.0.0

matrix:
  allow_failures:
    - rvm: rbx-19mode

script:
- CODECLIMATE_REPO_TOKEN=09bd983baf4d0c64d97c20a68baecde00cefb3db009a88792f23e3ce5eadf69a bundle exec rspec

notifications:
  email:
    - justin@jgrubbs.net

gemfile:
  - Gemfile


