module Carousel
  class Country

    COUNTRY_MAP = {
      "IE" => "IU", # Eire                          
      "BA" => "BA", # Bosnia Herzegovina            
      "AD" => "AD", # Andorra                       
      "AE" => "AE", # United Arab Emirates          
      "AF" => "AF", # Afghanistan                   
      "AG" => "AG", # Antigua                       
      "AI" => "AI", # Anguilla                      
      "AL" => "AL", # Albania                       
      "AM" => "AM", # Armenia                       
      "AN" => "AN", # Netherlands Antilles
      "AO" => "AO", # Angola                        
      "AR" => "AR", # Argentina                     
      "AS" => "PU", # American Samoa                
      "AT" => "AT", # Austria                       
      "AU" => "AU", # Australia                     
      "AW" => "UB", # Aruba                         
      "AZ" => "AZ", # Azerbaijan                    
      "BB" => "BB", # Barbados                      
      "BD" => "BD", # Bangladesh                    
      "BE" => "BE", # Belgium                       
      "BF" => "BK", # Burkina                       
      "BG" => "BG", # Bulgaria                      
      "BH" => "BH", # Bahrain                       
      "BI" => "BI", # Burundi                       
      "BJ" => "BJ", # Benin                         
      "BM" => "BM", # Bermuda                       
      "BN" => "BN", # Brunei                        
      "BO" => "BO", # Bolivia                       
      "BR" => "BR", # Brazil                        
      "BS" => "BS", # Bahamas                       
      "BT" => "BT", # Bhutan                        
      "BW" => "BW", # Botswana                      
      "BY" => "BY", # Belarus                       
      "BZ" => "BZ", # Belize                        
      "CA" => "CA", # Canada                        
      "CF" => "CF", # Central African Republic      
      "CG" => "CG", # Congo                         
      "CG" => "CD", # Congo
      "CH" => "CH", # Switzerland                   
      "CK" => "CK", # Cook Islands                  
      "CL" => "CL", # Chile                         
      "CM" => "CM", # Cameroon                      
      "CN" => "CN", # China                         
      "CO" => "CO", # Colombia                      
      "CR" => "CR", # Costa Rica                    
      "CU" => "CU", # Cuba                          
      "CV" => "CV", # Cape Verde                    
      "CY" => "CY", # Cyprus                        
      "CZ" => "CZ", # Czech Republic                
      "DE" => "DE", # Germany                       
      "DJ" => "DJ", # Djibouti                      
      "DK" => "DK", # Denmark                       
      "DM" => "DM", # Dominica                      
      "DO" => "DO", # Dominican Republic            
      "DZ" => "DZ", # Algeria                       
      "EC" => "EC", # Ecuador inc Galapagos Isl.    
      "EE" => "EE", # Estonia                       
      "EG" => "EG", # Egypt                         
      "ER" => "ER", # Eritrea                       
      "ES" => "ES", # Spain                         
      "ET" => "ET", # Ethiopia                      
      "FI" => "FI", # Finland                       
      "FJ" => "FJ", # Fiji                          
      "FK" => "FK", # Falkland Islands
      "FM" => "FM", # Micronesia                    
      "FO" => "FO", # Faroe Islands                 
      "FR" => "FR", # France                        
      "GA" => "GA", # Gabon                         
      "GB" => "UK", # United Kingdom                
      "GD" => "GD", # Grenada                       
      "GE" => "GE", # Georgia                       
      "GF" => "GF", # French Guiana                 
      "GH" => "GH", # Ghana                         
      "GI" => "GI", # Gibraltar                     
      "GL" => "GL", # Greenland                     
      "GM" => "GM", # Gambia                        
      "GN" => "GN", # Guinea                        
      "GP" => "LU", # Guadeloupe                    
      "GQ" => "GQ", # Equatorial Guinea             
      "GR" => "GR", # Greece                        
      "GT" => "GT", # Guatemala                     
      "GU" => "GU", # Guam                          
      "GY" => "GY", # Guyana                        
      "HK" => "HK", # Hong Kong                     
      "HN" => "HN", # Honduras                      
      "HR" => "HR", # Croatia                       
      "HT" => "HT", # Haiti                         
      "HU" => "HU", # Hungary                       
      "ID" => "ID", # Indonesia                     
      "IL" => "IL", # Israel                        
      "IN" => "IN", # India                         
      "IQ" => "IQ", # Iraq                          
      "IR" => "IR", # Iran                          
      "IS" => "IS", # Iceland                       
      "IT" => "IT", # Italy                         
      "JM" => "JM", # Jamaica                       
      "JO" => "JO", # Jordan                        
      "JP" => "JP", # Japan                         
      "KE" => "KE", # Kenya                         
      "KG" => "KG", # Kyrgyzstan                    
      "KH" => "KH", # Cambodia                      
      "KI" => "KI", # Kiribati                      
      "KM" => "KM", # Comoros                       
      "KN" => "KT", # St. Kitts                     
      "KP" => "FP", # North Korea                   
      "KR" => "KR", # South Korea                   
      "KW" => "KW", # Kuwait                        
      "KY" => "KY", # Cayman Islands                
      "KZ" => "KZ", # Kazakhstan                    
      "LB" => "LB", # Lebanon                       
      "LC" => "LC", # St Lucia                      
      "LI" => "LI", # Liechtenstein                 
      "LK" => "LK", # Sri Lanka                     
      "LR" => "LY", # Libya                         
      "LR" => "LR", # Liberia                       
      "LS" => "LS", # Lesotho                       
      "LT" => "LT", # Lithuania                     
      "LU" => "LX", # Luxembourg                    
      "LV" => "LV", # Latvia                        
      "MA" => "MA", # Morocco                       
      "MC" => "MC", # Monaco                        
      "MD" => "MD", # Moldova                       
      "MG" => "MG", # Madagascar                    
      "MH" => "MH", # Marshall Islands              
      "MK" => "MK", # Macedonia                     
      "ML" => "ML", # Mali                          
      "MN" => "MN", # Mongolia                      
      "MO" => "MO", # Macao                         
      "MQ" => "MQ", # Martinique                    
      "MR" => "MR", # Mauritania                    
      "MS" => "MS", # Montserrat                    
      "MT" => "MT", # Malta                         
      "MU" => "MU", # Mauritius                     
      "MV" => "MV", # Maldives                      
      "MW" => "MW", # Malawi                        
      "MX" => "MX", # Mexico                        
      "MY" => "MY", # Malaysia                      
      "MZ" => "MZ", # Mozambique                    
      "NA" => "NM", # Namibia                       
      "NC" => "NC", # New Caledonia + Depen.        
      "NE" => "NE", # Niger                         
      "NF" => "OK", # Norfolk Islands               
      "NG" => "NG", # Nigeria                       
      "NI" => "NI", # Nicaragua                     
      "NL" => "NL", # Netherlands                   
      "NO" => "NO", # Norway                        
      "NP" => "NP", # Nepal                         
      "NR" => "NR", # Nauru                         
      "NU" => "NU", # Niue                          
      "NZ" => "NZ", # New Zealand                   
      "OM" => "OM", # Oman                          
      "PA" => "PA", # Panama                        
      "PE" => "PE", # Peru                          
      "PF" => "PF", # French Polynesia              
      "PG" => "PG", # Papua New Guinea              
      "PH" => "PH", # Philippines                   
      "PK" => "PK", # Pakistan                      
      "PL" => "PD", # Poland                        
      "PR" => "PR", # Puerto Rico                   
      "PT" => "PT", # Portugal                      
      "PY" => "PY", # Paraguay                      
      "QA" => "QA", # Qatar                         
      "RE" => "RE", # Reunion                       
      "RO" => "RO", # Romania                       
      "RS" => "NT", # Serbia                        
      "RU" => "RU", # Russia                        
      "RW" => "RW", # Rwanda                        
      "SA" => "SA", # Saudi Arabia                  
      "SB" => "SB", # Solomon Islands               
      "SC" => "SC", # Seychelles                    
      "SD" => "SD", # Sudan                         
      "SE" => "SE", # Sweden                        
      "SG" => "SG", # Singapore                     
      "SI" => "SI", # Slovenia                      
      "SK" => "VV", # Slovakia                      
      "SL" => "SL", # Sierra Leone                  
      "SM" => "SM", # San Marino                    
      "SN" => "SN", # Senegal                       
      "SR" => "SR", # Surinam                       
      "SV" => "SV", # El Salvador                   
      "SY" => "SY", # Syria                         
      "SZ" => "SZ", # Swaziland                     
      "TC" => "TC", # Turks and Caicos Islands      
      "TD" => "TD", # Chad                          
      "TG" => "TG", # Togo                          
      "TH" => "TH", # Thailand                      
      "TJ" => "TJ", # Tajikistan                    
      "TM" => "TM", # Turkmenistan                  
      "TN" => "TN", # Tunisia                       
      "TR" => "TR", # Turkey                        
      "TT" => "TT", # Trinidad and Tobago           
      "TV" => "TV", # Tuvalu                        
      "TW" => "TW", # Taiwan                        
      "TZ" => "TZ", # Tanzania                      
      "UA" => "UA", # Ukraine                       
      "UG" => "UG", # Uganda                        
      "US" => "US", # United States of America      
      "UY" => "UY", # Uruguay                       
      "UZ" => "UZ", # Uzbekistan                    
      "VC" => "VC", # St Vincent                    
      "VE" => "VE", # Venezuela                     
      "VI" => "VI", # Virgin Islands of USA         
      "VN" => "VN", # Vietnam                       
      "VU" => "VU", # Vanuatu                       
      "WF" => "WF", # Wallis and Futuna Islands     
      "YE" => "YE", # Yemen                         
      "ZA" => "ZA", # South Africa                  
      "ZM" => "ZM", # Zambia                        
      "ZW" => "ZW", # Zimbabwe                      
      "IM" => "IM", # Isle of Man
      "JE" => "JE"  # Jersey
    }

    def self.map(code)
      COUNTRY_MAP[code] || code
    end

  end
end
